server:
  port: 8003
spring:
  application:
    name: cloud-openfeign-service
  cloud:
    consul:
      host: 192.168.111.128
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
#        heartbeat:
#          enabled: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 1000
      httpclient:
        hc5:
          enabled: true
