server:
  port: 8003
spring:
  application:
    name: cloud-openfeign-service
  cloud:
    consul:
      host: 192.168.111.128
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
#        heartbeat:
#          enabled: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 1000
      httpclient:
        hc5:
          enabled: true
#开启openfeign自带的日志打印功能固定写法
#logging.level + feign接口全路径+类名 + debug
#并且要配置openfeign日志开启
logging:
  level:
    com:
      mk:
        cloud:
          apis:
            PayFeignApi: debug

